name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: mathwebservice
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKERHUB_PWD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    name: Build Container

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Build image
        run: |
          docker build -t $IMAGE_NAME .
      - name: Docker Login
        run: |
          docker login -u doddahulugappa -p Huli123#
      - name: Docker tag
        run: |
          docker tag $IMAGE_NAME doddahulugappa/fastapi:v$(date +%s)
      - name: Push Image
        run: |
          docker push doddahulugappa/fastapi:v$(date +%s)