name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: doddahulugappa/mathwebservice
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build:
    name: Build Container

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Build image and publish to registry
        run: |
          docker build -t $IMAGE_NAME:latest .
          echo $DOCKERHUB_TOKEN | docker login -u $DOCKER_USER --password-stdin
          docker push $IMAGE_NAME:latest